# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='category',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='idea',
            name='likes',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
