# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_auto_20170121_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='id',
            new_name='uuid',
        ),
    ]
