# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 04:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_auto_20170121_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='uuid',
            new_name='id',
        ),
    ]
